# Generated by Django 3.2.13 on 2022-08-10 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993/9/2'),
            preserve_default=False,
        ),
    ]
